# Capstone Project - The Battle of Neighborhoods

This is my Final Project for Course IBM Data Science Professional Certificate.

### I. Introduction

This report is for the final course of the Data Science Specialization. A 9-courses series created by IBM, hosted on Coursera platform. The problem and the analysis approach are left for the learner to decide, with a requirement of leveraging the Foursquare location data to explore or compare neighborhoods or cities of your choice or to come up with a problem that you can use the Foursquare location data to solve.

### II.	Business Problem:

The objective of this final assignment is to analyze and select best locations Ha Noi to open new coffee house. I use data science methodology and machine learning techniques that have learned through 9 course in IBM Data Science Professional Certificate such as data collection, data cleaning, Foursquare location data, clustering to answer the business question: where to open new coffee how in Hanoi. Of course, In the scope of capstone, I just mention some factors that effect the result. In order to launch this in real, we have to improve more. With this report, I show that I can use Python data science tools to solve business problem.

#### Import package geopy, folium and gieocoder

In [1]:
!conda install -c conda-forge geopy --yes

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

In [2]:
!conda install -c conda-forge folium=0.5.0 --yes

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

In [3]:
!conda install -c conda-forge geocoder --y

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

### Import Libraries to use in this project

In [4]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans


import folium # map rendering library

print('Libraries imported.')

Libraries imported.

### Function get_latlng() to get latitude and logitude from adress

In [5]:
import  geocoder
# define a function to get coordinates
def get_latlng(neighborhood):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Ha Noi, VietNam'.format(neighborhood))
        lat_lng_coords =[neighborhood] + g.latlng
        print (neighborhood)
        print(lat_lng_coords)
    return lat_lng_coords

### Preparing Data

In [6]:
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner

link = "https://raw.githubusercontent.com/nxtacctau/Coursera_Capstone/master/HanoiCSV.txt"
df1 = pd.read_csv(link)

df1.head()

  Provincial Cities/Districts[21]  Area (km2)[21] Population[21]
0                         Ba Đình           9.224        247,100
1                     Bắc Từ Liêm          43.350        333,300
2                        Cầu Giấy          12.040        266,800
3                         Đống Đa           9.960        420,900
4                    Hai Bà Trưng          10.090        318,000

In [7]:
df1.columns =["neighborhood","Area","Pop"]

In [8]:
# print the number of rows of the dataframe
df1.shape

(13, 3)

In [9]:
df1.head()

   neighborhood    Area      Pop
0       Ba Đình   9.224  247,100
1   Bắc Từ Liêm  43.350  333,300
2      Cầu Giấy  12.040  266,800
3       Đống Đa   9.960  420,900
4  Hai Bà Trưng  10.090  318,000

#### Use get_latlgn() function to get coordinate and store in a new list

In [10]:
# call the function to get the coordinates, store in a new list using list comprehension
coords =[get_latlng(neighborhood) for neighborhood in df1["neighborhood"].tolist() ]
coords

Ba Đình
['Ba Đình', 21.022010000000023, 105.81934000000007]
Bắc Từ Liêm
['Bắc Từ Liêm', 21.062170000000037, 105.76941000000005]
Cầu Giấy
['Cầu Giấy', 21.030244783314533, 105.80135903284247]
Đống Đa
['Đống Đa', 20.996982726368117, 105.88269543781095]
Hai Bà Trưng
['Hai Bà Trưng', 21.155050000000074, 105.73429000000004]
Hoàn Kiếm
['Hoàn Kiếm', 21.07906999942315, 105.81928008050087]
Hoàng Mai
['Hoàng Mai', 21.028579952247846, 105.83206997446484]
Long Biên
['Long Biên', 21.044537403629857, 105.86187883301236]
Nam Từ Liêm
['Nam Từ Liêm', 21.00813000000005, 105.76650000000006]
Tây Hồ
['Tây Hồ', 21.066670000000045, 105.83333000000005]
Thanh Xuân
['Thanh Xuân', 21.037600000000054, 105.77507000000008]
Đông Anh
['Đông Anh', 21.154180000000053, 105.85131000000007]
Gia Lâm
['Gia Lâm', 21.016521292923876, 105.92102729292387]

[['Ba Đình', 21.022010000000023, 105.81934000000007],
 ['Bắc Từ Liêm', 21.062170000000037, 105.76941000000005],
 ['Cầu Giấy', 21.030244783314533, 105.80135903284247],
 ['Đống Đa', 20.996982726368117, 105.88269543781095],
 ['Hai Bà Trưng', 21.155050000000074, 105.73429000000004],
 ['Hoàn Kiếm', 21.07906999942315, 105.81928008050087],
 ['Hoàng Mai', 21.028579952247846, 105.83206997446484],
 ['Long Biên', 21.044537403629857, 105.86187883301236],
 ['Nam Từ Liêm', 21.00813000000005, 105.76650000000006],
 ['Tây Hồ', 21.066670000000045, 105.83333000000005],
 ['Thanh Xuân', 21.037600000000054, 105.77507000000008],
 ['Đông Anh', 21.154180000000053, 105.85131000000007],
 ['Gia Lâm', 21.016521292923876, 105.92102729292387]]

In [11]:
df2 = pd.DataFrame(coords)
df2.head(123)

               0          1           2
0        Ba Đình  21.022010  105.819340
1    Bắc Từ Liêm  21.062170  105.769410
2       Cầu Giấy  21.030245  105.801359
3        Đống Đa  20.996983  105.882695
4   Hai Bà Trưng  21.155050  105.734290
5      Hoàn Kiếm  21.079070  105.819280
6      Hoàng Mai  21.028580  105.832070
7      Long Biên  21.044537  105.861879
8    Nam Từ Liêm  21.008130  105.766500
9         Tây Hồ  21.066670  105.833330
10    Thanh Xuân  21.037600  105.775070
11      Đông Anh  21.154180  105.851310
12       Gia Lâm  21.016521  105.921027

In [12]:
df2.columns =["neighborhood","Latitude","Longitude"]
df2.head(13)

    neighborhood   Latitude   Longitude
0        Ba Đình  21.022010  105.819340
1    Bắc Từ Liêm  21.062170  105.769410
2       Cầu Giấy  21.030245  105.801359
3        Đống Đa  20.996983  105.882695
4   Hai Bà Trưng  21.155050  105.734290
5      Hoàn Kiếm  21.079070  105.819280
6      Hoàng Mai  21.028580  105.832070
7      Long Biên  21.044537  105.861879
8    Nam Từ Liêm  21.008130  105.766500
9         Tây Hồ  21.066670  105.833330
10    Thanh Xuân  21.037600  105.775070
11      Đông Anh  21.154180  105.851310
12       Gia Lâm  21.016521  105.921027

In [13]:
df2.to_csv(r'Distric_withGeo.csv')

#### Create a map of Hanoi from information of neighborhood

In [19]:
# Create a map of Hanoi superimposed on top

# get the coordinates of Ha Noi
address = 'Hà Nội, Việt Nam'

geolocator = Nominatim(user_agent="my-application")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Ha Noi, Viet Nam {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Ha Noi, Viet Nam 21.0294498, 105.8544441.

In [20]:
# create map of Hanoi using latitude and longitude values
map_hn = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, neighborhood in zip(df2['Latitude'], df2['Longitude'], df2['neighborhood']):
    label = '{}'.format(neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=10,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7).add_to(map_hn)  
    
map_hn

In [16]:
# save the map as HTML file
map_hn.save('map_hn.html')

## Use the Foursquare API to explore the neighborhoods

In [21]:
# 5. Use the Foursquare API to explore the neighborhoods

# define Foursquare Credentials and Version
CLIENT_ID = '5VKNRCQUOZLNWJZX2XIVK2RVDAJBCPTPUHZT1BJGE12KGIYZ' # your Foursquare ID
CLIENT_SECRET = 'LLOOJEFION04GHZ5XQ4MIS4MP45MO3QUMUKGIXHETA1GT2OT' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 5VKNRCQUOZLNWJZX2XIVK2RVDAJBCPTPUHZT1BJGE12KGIYZ
CLIENT_SECRET:LLOOJEFION04GHZ5XQ4MIS4MP45MO3QUMUKGIXHETA1GT2OT

In [23]:
# Get the top 100 venues that are within a radius of 7000 meters.
radius =7000
LIMIT = 100

venues = []

for lat, long, Dist in zip(df2['Latitude'], df2['Longitude'], df2['neighborhood']):
    
    # create the API request URL
    url = "https://api.foursquare.com/v2/venues/explore?client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}".format(
        CLIENT_ID,
        CLIENT_SECRET,
        VERSION,
        lat,
        long,
        radius, 
        LIMIT)
    
    # make the GET request
    results = requests.get(url).json()["response"]['groups'][0]['items']
    
    # return only relevant information for each nearby venue
    for venue in results:
        venues.append((
            Dist,
            lat, 
            long, 
            venue['venue']['name'], 
            venue['venue']['location']['lat'], 
            venue['venue']['location']['lng'],  
            venue['venue']['categories'][0]['name']))

In [24]:
# convert the venues list into a new DataFrame
venues_df = pd.DataFrame(venues)

# define the column names
venues_df.columns = ['neighborhood', 'Latitude', 'Longitude', 'VenueName', 'VenueLatitude', 'VenueLongitude', 'VenueCategory']

print(venues_df.shape)
venues_df.head()

(1045, 7)

,neighborhood,Latitude,Longitude,VenueName,VenueLatitude,VenueLongitude,VenueCategory
0,Ba Đình,21.02201,105.81934,Pizza 4P,21.034181,105.812777,Pizza Place
1,Ba Đình,21.02201,105.81934,Văn Miếu Quốc Tử Giám (Temple of Literature) (...,21.028707,105.836005,Confucian Temple
2,Ba Đình,21.02201,105.81934,Lotte Hotel Hanoi,21.032241,105.812817,Hotel
3,Ba Đình,21.02201,105.81934,Sky Walk Lotte Centre,21.032131,105.812428,Scenic Lookout
4,Ba Đình,21.02201,105.81934,Hotel La Siesta Trendy,21.032244,105.845727,Hotel

In [25]:
venues_df.groupby(["neighborhood"]).count()

,Latitude,Longitude,VenueName,VenueLatitude,VenueLongitude,VenueCategory
neighborhood,,,,,,
Ba Đình,100,100,100,100,100,100
Bắc Từ Liêm,81,81,81,81,81,81
Cầu Giấy,100,100,100,100,100,100
Gia Lâm,53,53,53,53,53,53
Hai Bà Trưng,4,4,4,4,4,4
Hoàn Kiếm,100,100,100,100,100,100
Hoàng Mai,100,100,100,100,100,100
Long Biên,100,100,100,100,100,100
Nam Từ Liêm,100,100,100,100,100,100
Thanh Xuân,100,100,100,100,100,100
Tây Hồ,100,100,100,100,100,100
Đông Anh,7,7,7,7,7,7
Đống Đa,100,100,100,100,100,100

In [26]:
# Find out how many unique categories can be curated from all the returned venues
print('There are {} uniques categories.'.format(len(venues_df['VenueCategory'].unique())))

There are 86 uniques categories.

In [27]:
# print out the list of categories
venues_df['VenueCategory'].unique()[:250]

array(['Pizza Place', 'Confucian Temple', 'Hotel', 'Scenic Lookout',
       'Beer Bar', 'Noodle House', 'Art Gallery', 'Brewery',
       'Coffee Shop', 'Park', 'Vietnamese Restaurant', 'Bistro',
       'Italian Restaurant', 'Sandwich Place', 'Café', 'Chocolate Shop',
       'French Restaurant', 'Supermarket',
       'Vegetarian / Vegan Restaurant', 'Japanese Restaurant',
       'Wings Joint', 'Movie Theater', 'Steakhouse', 'Cocktail Bar',
       'Fast Food Restaurant', 'Asian Restaurant', 'Temple', 'Spa',
       'Museum', 'Multiplex', 'Hotel Bar', 'Beer Garden', 'Hostel',
       'Dessert Shop', 'BBQ Joint', 'Korean Restaurant', 'Golf Course',
       'Mexican Restaurant', 'Modern European Restaurant',
       'Ice Cream Shop', 'Sushi Restaurant', 'Furniture / Home Store',
       'Lounge', 'Rock Club', 'Sports Bar', 'Bakery', 'Wine Bar',
       'Stadium', 'Cantonese Restaurant', 'Gym / Fitness Center',
       'Buffet', 'Bubble Tea Shop', 'Szechuan Restaurant',
       'Malay Restaurant', 'Shopping Mall', 'Hotpot Restaurant',
       'Climbing Gym', 'Mobile Phone Shop', 'Buddhist Temple', 'Gym',
       'Restaurant', 'Bowling Alley', 'Jazz Club', 'Village',
       'Opera House', 'Pub', 'Monument / Landmark', 'Burger Joint',
       'Tiki Bar', 'Lake', 'Food Truck', 'Tea Room', 'Tibetan Restaurant',
       'Massage Studio', 'Market', 'Food Court', 'Art Museum',
       'Grocery Store', 'Pedestrian Plaza', 'Pastry Shop',
       'Burmese Restaurant', 'Bar', 'Bike Trail', 'Australian Restaurant',
       'Housing Development', 'Pakistani Restaurant'], dtype=object)

In [28]:
# check if the results contain "Shopping Mall"
"neighborhood" in venues_df['VenueCategory'].unique()

# one hot encoding
hn_onehot = pd.get_dummies(venues_df[['VenueCategory']], prefix="", prefix_sep="")

# add Dist column back to dataframe
hn_onehot['neighborhood'] = venues_df['neighborhood'] 

# move Dist column to the first column
fixed_columns = [hn_onehot.columns[-1]] + list(hn_onehot.columns[:-1])
hn_onehot = hn_onehot[fixed_columns]

print(hn_onehot.shape)
hn_onehot.head()

(1045, 87)

,neighborhood,Art Gallery,Art Museum,Asian Restaurant,Australian Restaurant,BBQ Joint,Bakery,Bar,Beer Bar,Beer Garden,Bike Trail,Bistro,Bowling Alley,Brewery,Bubble Tea Shop,Buddhist Temple,Buffet,Burger Joint,Burmese Restaurant,Café,Cantonese Restaurant,Chocolate Shop,Climbing Gym,Cocktail Bar,Coffee Shop,Confucian Temple,Dessert Shop,Fast Food Restaurant,Food Court,Food Truck,French Restaurant,Furniture / Home Store,Golf Course,Grocery Store,Gym,Gym / Fitness Center,Hostel,Hotel,Hotel Bar,Hotpot Restaurant,Housing Development,Ice Cream Shop,Italian Restaurant,Japanese Restaurant,Jazz Club,Korean Restaurant,Lake,Lounge,Malay Restaurant,Market,Massage Studio,Mexican Restaurant,Mobile Phone Shop,Modern European Restaurant,Monument / Landmark,Movie Theater,Multiplex,Museum,Noodle House,Opera House,Pakistani Restaurant,Park,Pastry Shop,Pedestrian Plaza,Pizza Place,Pub,Restaurant,Rock Club,Sandwich Place,Scenic Lookout,Shopping Mall,Spa,Sports Bar,Stadium,Steakhouse,Supermarket,Sushi Restaurant,Szechuan Restaurant,Tea Room,Temple,Tibetan Restaurant,Tiki Bar,Vegetarian / Vegan Restaurant,Vietnamese Restaurant,Village,Wine Bar,Wings Joint
0,Ba Đình,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Ba Đình,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Ba Đình,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Ba Đình,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Ba Đình,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
hn_grouped = hn_onehot.groupby(["neighborhood"]).mean().reset_index()

print(hn_grouped.shape)
hn_grouped

(13, 87)

,neighborhood,Art Gallery,Art Museum,Asian Restaurant,Australian Restaurant,BBQ Joint,Bakery,Bar,Beer Bar,Beer Garden,Bike Trail,Bistro,Bowling Alley,Brewery,Bubble Tea Shop,Buddhist Temple,Buffet,Burger Joint,Burmese Restaurant,Café,Cantonese Restaurant,Chocolate Shop,Climbing Gym,Cocktail Bar,Coffee Shop,Confucian Temple,Dessert Shop,Fast Food Restaurant,Food Court,Food Truck,French Restaurant,Furniture / Home Store,Golf Course,Grocery Store,Gym,Gym / Fitness Center,Hostel,Hotel,Hotel Bar,Hotpot Restaurant,Housing Development,Ice Cream Shop,Italian Restaurant,Japanese Restaurant,Jazz Club,Korean Restaurant,Lake,Lounge,Malay Restaurant,Market,Massage Studio,Mexican Restaurant,Mobile Phone Shop,Modern European Restaurant,Monument / Landmark,Movie Theater,Multiplex,Museum,Noodle House,Opera House,Pakistani Restaurant,Park,Pastry Shop,Pedestrian Plaza,Pizza Place,Pub,Restaurant,Rock Club,Sandwich Place,Scenic Lookout,Shopping Mall,Spa,Sports Bar,Stadium,Steakhouse,Supermarket,Sushi Restaurant,Szechuan Restaurant,Tea Room,Temple,Tibetan Restaurant,Tiki Bar,Vegetarian / Vegan Restaurant,Vietnamese Restaurant,Village,Wine Bar,Wings Joint
0,Ba Đình,0.010000,0.00,0.010000,0.000000,0.010000,0.000000,0.000000,0.02,0.01,0.000000,0.01,0.000000,0.010000,0.000000,0.00,0.000000,0.00,0.000000,0.060000,0.000000,0.01,0.00,0.01,0.130000,0.01,0.01,0.010000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.000000,0.000000,0.01,0.170000,0.010000,0.000000,0.000000,0.000000,0.030000,0.010000,0.000000,0.010000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,0.01,0.010000,0.010000,0.070000,0.000000,0.000000,0.020000,0.00,0.00,0.020000,0.00,0.000000,0.000000,0.03,0.010000,0.000000,0.030000,0.000000,0.000000,0.010000,0.020000,0.000000,0.000000,0.00,0.01,0.00,0.00,0.01,0.160000,0.000000,0.000000,0.01
1,Bắc Từ Liêm,0.012346,0.00,0.024691,0.000000,0.049383,0.037037,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.012346,0.012346,0.00,0.012346,0.00,0.000000,0.086420,0.012346,0.00,0.00,0.00,0.049383,0.00,0.00,0.000000,0.000000,0.00,0.024691,0.012346,0.012346,0.00,0.000000,0.012346,0.00,0.135802,0.024691,0.012346,0.000000,0.012346,0.012346,0.049383,0.000000,0.037037,0.00,0.012346,0.012346,0.000000,0.00,0.024691,0.00,0.012346,0.00,0.00,0.012346,0.012346,0.012346,0.000000,0.000000,0.024691,0.00,0.00,0.037037,0.00,0.000000,0.012346,0.00,0.012346,0.024691,0.000000,0.012346,0.012346,0.012346,0.024691,0.012346,0.012346,0.00,0.00,0.00,0.00,0.00,0.037037,0.000000,0.012346,0.00
2,Cầu Giấy,0.010000,0.00,0.010000,0.000000,0.020000,0.000000,0.000000,0.02,0.00,0.000000,0.01,0.000000,0.020000,0.000000,0.01,0.000000,0.00,0.000000,0.030000,0.000000,0.01,0.01,0.01,0.130000,0.01,0.00,0.010000,0.000000,0.00,0.010000,0.010000,0.010000,0.00,0.000000,0.020000,0.00,0.150000,0.000000,0.000000,0.000000,0.010000,0.020000,0.020000,0.000000,0.020000,0.00,0.010000,0.000000,0.000000,0.00,0.010000,0.01,0.010000,0.00,0.01,0.000000,0.010000,0.050000,0.000000,0.000000,0.020000,0.00,0.00,0.020000,0.00,0.000000,0.000000,0.02,0.010000,0.000000,0.030000,0.000000,0.000000,0.010000,0.020000,0.010000,0.000000,0.00,0.01,0.00,0.00,0.01,0.140000,0.000000,0.000000,0.01
3,Gia Lâm,0.000000,0.00,0.000000,0.018868,0.037736,0.000000,0.018868,0.00,0.00,0.018868,0.00,0.018868,0.000000,0.000000,0.00,0.000000,0.00,0.018868,0.056604,0.000000,0.00,0.00,0.00,0.037736,0.00,0.00,0.018868,0.018868,0.00,0.018868,0.018868,0.018868,0.00,0.018868,0.000000,0.00,0.075472,0.037736,0.000000,0.018868,0.018868,0.018868,0.000000,0.018868,0.000000,0.00,0.018868,0.000000,0.018868,0.00,0.000000,0.00,0.000000,0.00,0.00,0.037736,0.000000,0.056604,0.018868,0.018868,0.018868,0.00,0.00,0.018868,0.00,0.018868,0.000000,0.00,0.000000,0.037736,0.018868,0.000000,0.000000,0.018868,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00,0.150943,0.018868,0.000000,0.00
4,Hai Bà Trưng,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.000000,0.00,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,0.00,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.00
5,Hoàn Kiếm,0.010000,0.00,0.000000,0.000000,0.010000,0.010000,0.000000,0.01,0.01,0.000000,0.01,0.000000,0.020000,0.000000,0.01,0.000000,0.00,0.000000,0.070000,0.000000,0.00,0.01,0.01,0.130000,0.01,0.03,0.000000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.000000,0.010000,0.02,0.140000,0.020000,0.000000,0.000000,0.010000,0.010000,0.010000,0.000000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.020000,0.00,0.010000,0.00,0.00,0.000000,0.010000,0.070000,0.000000,0.000000,0.020000,0.00,0.00,0.020000,0.00,0.000000,0.010000,0.02,0.010000,0.000000,0.030000,0.010000,0.000000,0.010000,0.000000,0.010000,0.000000,0.00,0.01,0.00,0.00,0.00,0.140000,0.000000,0.010000,0.00
6,Hoàng Mai,0.010000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.01,0.01,0.000000,0.01,0.000000,0.010000,0.000000,0.00,0.000000,0.00,0.000000,0.050000,0.000000,0.01,0.01,0.01,0.160000,0.01,0.02,0.010000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.000000,0.000000,0.02,0.190000,0.010000,0.000000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.01,0.00,0.000000,0.000000,0.080000,0.000000,0.000000,0.010000,0.00,0.00,0.020000,0.01,0.000000,0.000000,0.03,0.010000,0.000000,0.030000,0.000000,0.000000,0.010000,0.010000,0.000000,0.000000,0.00,0.01,0.00,0.00,0.01,0.170000,0.000000,0.000000,0.01
7,Long Biên,0.000000,0.00,0.000000,0.000000,0.010000,0.000000,0.000000,0.01,0.01,0.000000,0.01,0.000000,0.010000,0.000000,0.00,0.000000,0.01,0.000000,0.050000,0.000000,0.01,0.01,0.01,0.150000,0.01,0.03,0.010000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.000000,0.010000,0.02,0.170000,0.020000,0.000000,0.000000,0.000000,0.010000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.000000,0.110000,0.000000,0.000000,0.000000,0.00,0.00,0.010000,0.01,0.010000,0.000000,0.02,0.000000,0.000000,0.040000,0.000000,0.000000,0.010000,0.010000,0.000000,0.000000,0.00,0.02,0.00,0.00,0.02,0.160000,0.000000,0.000000,0.00
8,Nam Từ Liêm,0.010000,0.01,0.010000,0.000000,0.030000,0.040000,0.000000,0.03,0.00,0.000000,0.00,0.000000,0.000000,0.010000,0.00,0.010000,0.00,0.000000,0.050000,0.010000,0.00,0.00,0.00,0.080000,0.00,0.01,0.000000,0.010000,0.01,0.010000,0.010000,0.010000,0.01,0.000000,0.010000,0.00,0.090000,0.010000,0.010000,0.000000,0.010000,0.000000,0.040000,0.000000,0.040000,0.01,0.000000,0.010000,0.020000,0.01,0.000000,0.02,0.000000,0.00,0.02,0.060000,0.010000,0.010000,0.000000,0.000000,0.020000,0.00,0.01,0.030000,0.00,0.010000,0.010000,0.01,0.010000,0.010000,0.010000,0.000000,0.010000,0.010000,0.020000,0.000000,0.010000,0.02,0.00,0.01,0.01,0.01,0.040000,0.000000,0.000000,0.00
9,Thanh Xuân,0.010000,0.00,0.010000,0.000000,0.030000,0.020000,0.000000,0.02,0.00,0.000000,0.00,0.000000,0.010000,0.000000,0.01,0.010000,0.00,0.000000,0.050000,0.010000,0.00,0.00,0.00,0.090000,0.01,0.01,0.000000,0.010000,0.01,0.020000,0.010000,0.010000,0.00,0.000000,0.020000,0.00,0.120000,0.010000,0.020000,0.000000,0.010000,0.010000,0.040000,0.000000,0.020000,0.01,0.010000,0.000000,0.000000,0.02,0.010000,0.02,0.010000,0.00,0.01,0.030000,0.010000,0.000000,0.000000,0.000000,0.020000,0.01,0.00,0.020000,0.00,0.000000,0.020000,0.00,0.010000,0.000000,0.000000,0.010000,0.010000,0.010000,0.010000,0.010000,0.000000,0.01,0.01,0.01,0.01,0.00,0.080000,0.000000,0.010000,0.01
10,Tây Hồ,0.010000,0.00,0.000000,0.000000,0.010000,0.010000,0.000000,0.01,0.01,0.000000,0.01,0.000000,0.020000,0.000000,0.01,0.000000,0.00,0.000000,0.060000,0.000000,0.00,0.01,0.01,0.150000,0.01,0.03,0.010000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.000000,0.010000,0.02,0.150000,0.020000,0.000000,0.000000,0.010000,0.020000,0.000000,0.000000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.020000,0.00,0.010000,0.00,0.00,0.000000,0.000000,0.070000,0.000000,0.000000,0.000000,0.00,0.00,0.020000,0.00,0.000000,0.010000,0.02,0.000000,0.000000,0.030000,0.010000,0.000000,0.020000,0.000000,0.010000,0.000000,0.00,0.01,0.00,0.00,0.00,0.140000,0.000000,0.010000,0.00
11,Đông Anh,0.000000,0.00,0.142857,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.000000,0.00,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,0.571429,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000,0.000000,0.00,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.00
12,Đống Đa,0.000000,0.00,0.000000,0.000000,0.030000,0.000000,0.000000,0.00,0.01,0.000000,0.01,0.010000,0.010000,0.000000,0.00,0.000000,0.00,0.000000,0.040000,0.000000,0.01,0.00,0.01,0.140000,0.01,0.02,0.010000,0.000000,0.00,0.010000,0.010000,0.010000,0.00,0.010000,0.000000,0.03,0.140000,0.020000,0.010000,0.000000,0.010000,0.020000,0.010000,0.010000,0.000000,0.00,0.010000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,0.00,0.010000,0.000000,0.070000,0.010000,0.000000,0.010000,0.00,0.00,0.010000,0.00,0.010000,0.000000,0.03,0.000000,0.010000,0.020000,0.000000,0.000000,0.010000,0.010000,0.000000,0.000000,0.00,0.01,0.00,0.00,0.01,0.160000,0.010000,0.000000,0.00

In [42]:
len(hn_grouped[hn_grouped["Spa"] > 0])

9

In [54]:
hn_mall = hn_grouped[["neighborhood","Spa"]]
hn_mall.head()

   neighborhood       Spa
0       Ba Đình  0.030000
1   Bắc Từ Liêm  0.000000
2      Cầu Giấy  0.030000
3       Gia Lâm  0.018868
4  Hai Bà Trưng  0.000000

In [55]:
# set number of clusters
kclusters = 3

hn_clustering = hn_mall.drop(["neighborhood"], 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(hn_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([2, 1, 2, 0, 1, 2, 2, 2, 0, 1])

In [56]:
# create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
hn_merged = hn_mall.copy()

# add clustering labels
hn_merged["Cluster Labels"] = kmeans.labels_

In [57]:
hn_merged.head()

   neighborhood       Spa  Cluster Labels
0       Ba Đình  0.030000               2
1   Bắc Từ Liêm  0.000000               1
2      Cầu Giấy  0.030000               2
3       Gia Lâm  0.018868               0
4  Hai Bà Trưng  0.000000               1

In [58]:
# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
hn_merged_SM = hn_merged.join(df2.set_index("neighborhood"), on="neighborhood")

print(hn_merged_SM.shape)
hn_merged_SM.head() # check the last columns!

(13, 5)

   neighborhood       Spa  Cluster Labels   Latitude   Longitude
0       Ba Đình  0.030000               2  21.022010  105.819340
1   Bắc Từ Liêm  0.000000               1  21.062170  105.769410
2      Cầu Giấy  0.030000               2  21.030245  105.801359
3       Gia Lâm  0.018868               0  21.016521  105.921027
4  Hai Bà Trưng  0.000000               1  21.155050  105.734290

In [59]:
print(hn_merged_SM.shape)
hn_merged_SM.sort_values(["Cluster Labels"], inplace=True)
hn_merged_SM

(13, 5)

    neighborhood       Spa  Cluster Labels   Latitude   Longitude
3        Gia Lâm  0.018868               0  21.016521  105.921027
8    Nam Từ Liêm  0.010000               0  21.008130  105.766500
12       Đống Đa  0.020000               0  20.996983  105.882695
1    Bắc Từ Liêm  0.000000               1  21.062170  105.769410
4   Hai Bà Trưng  0.000000               1  21.155050  105.734290
9     Thanh Xuân  0.000000               1  21.037600  105.775070
11      Đông Anh  0.000000               1  21.154180  105.851310
0        Ba Đình  0.030000               2  21.022010  105.819340
2       Cầu Giấy  0.030000               2  21.030245  105.801359
5      Hoàn Kiếm  0.030000               2  21.079070  105.819280
6      Hoàng Mai  0.030000               2  21.028580  105.832070
7      Long Biên  0.040000               2  21.044537  105.861879
10        Tây Hồ  0.030000               2  21.066670  105.833330

In [60]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(hn_merged_SM['Latitude'], hn_merged_SM['Longitude'], hn_merged_SM['neighborhood'], hn_merged_SM['Cluster Labels']):
    label = folium.Popup(str(poi) + ' - Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=10,
        popup=label,
        color=rainbow[cluster-3],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [61]:

# save the map as HTML file
map_clusters.save('map_clusters_SM.html')

In [65]:
hn_merged_SM.loc[hn_merged_SM['Cluster Labels'] == 0]

   neighborhood       Spa  Cluster Labels   Latitude   Longitude
3       Gia Lâm  0.018868               0  21.016521  105.921027
8   Nam Từ Liêm  0.010000               0  21.008130  105.766500
12      Đống Đa  0.020000               0  20.996983  105.882695

In [66]:
hn_merged_SM.loc[hn_merged_SM['Cluster Labels'] == 1]

    neighborhood  Spa  Cluster Labels  Latitude  Longitude
1    Bắc Từ Liêm  0.0               1  21.06217  105.76941
4   Hai Bà Trưng  0.0               1  21.15505  105.73429
9     Thanh Xuân  0.0               1  21.03760  105.77507
11      Đông Anh  0.0               1  21.15418  105.85131

In [67]:
hn_merged_SM.loc[hn_merged_SM['Cluster Labels'] == 2]

   neighborhood   Spa  Cluster Labels   Latitude   Longitude
0       Ba Đình  0.03               2  21.022010  105.819340
2      Cầu Giấy  0.03               2  21.030245  105.801359
5     Hoàn Kiếm  0.03               2  21.079070  105.819280
6     Hoàng Mai  0.03               2  21.028580  105.832070
7     Long Biên  0.04               2  21.044537  105.861879
10       Tây Hồ  0.03               2  21.066670  105.833330